#:schema node_modules/wrangler/config-schema.json
name = "home"
main = ".open-next/worker.js"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = ".open-next/assets"

[vars]
# Add environment variables here if needed
